name: pyt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py39h6a678d5_0
  - executing=2.0.1=pyhd8ed1ab_0
  - grpcio=1.62.2=py39h6a678d5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=23_linux64_openblas
  - libcblas=3.9.0=23_linux64_openblas
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgfortran-ng=13.2.0=h69a702a_13
  - libgfortran5=13.2.0=h3d2ce59_13
  - libgomp=13.2.0=hc881cc4_6
  - libgrpc=1.62.2=h2d74bed_0
  - liblapack=3.9.0=23_linux64_openblas
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py39h06a4308_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - protobuf=4.25.3=py39h12ddb61_0
  - psutil=5.9.8=py39hd1e30aa_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.9.19=h955ad1f_0
  - python_abi=3.9=2_cp39
  - pyzmq=25.1.2=py39h6a678d5_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorboard=2.17.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39hd4f0224_1
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4=py39hd1e30aa_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - addict==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - astroid==3.1.0
      - async-timeout==4.0.3
      - asyncssh==2.14.2
      - atomicwrites==1.4.1
      - attrs==23.2.0
      - autopep8==2.0.4
      - av==12.3.0
      - babel==2.14.0
      - backports-tarfile==1.1.1
      - beautifulsoup4==4.12.3
      - bidict==0.23.1
      - binaryornot==0.4.4
      - biosppy==2.2.2
      - black==24.4.2
      - bleach==6.1.0
      - blis==1.0.1
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - chumpy==0.70
      - click==8.1.7
      - cloudpathlib==0.20.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - confection==0.1.5
      - confidenceinterval==1.0.5
      - contourpy==1.2.1
      - cookiecutter==2.6.0
      - cramjam==2.8.3
      - crcmod==1.7
      - cryptography==42.0.5
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.10
      - decorator==4.4.2
      - decord==0.6.0
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - diff-match-patch==20230430
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-to-markdown==0.15
      - docutils==0.21.2
      - easydev==0.13.2
      - einops==0.8.0
      - empatches==0.2.3
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - fastai==2.7.18
      - fastcore==1.7.19
      - fastdownload==0.0.7
      - fastjsonschema==2.19.1
      - fastparquet==2024.5.0
      - fastprogress==1.0.3
      - filelock==3.13.4
      - flake8==7.1.1
      - fmutils==0.2.2
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gray2color==0.4.3
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.23.0
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - imagesize==1.4.1
      - imbalanced-learn==0.12.4
      - imgviz==1.7.5
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - iopath==0.1.10
      - ipywidgets==8.1.3
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jeepney==0.8.0
      - jellyfish==1.0.3
      - jinja2==3.1.3
      - jmespath==0.10.0
      - joblib==1.4.0
      - json-tricks==3.17.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.11
      - keyring==25.2.0
      - kiwisolver==1.4.5
      - langcodes==3.4.1
      - language-data==1.2.0
      - lapx==0.5.9.post1
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - line-profiler==4.1.3
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.4
      - mmpose==1.3.1
      - mock==5.1.0
      - model-index==0.1.11
      - more-itertools==10.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - munkres==1.1.4
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - networkx==3.2.1
      - nolds==0.6.1
      - numba==0.60.0
      - numpy==1.26.3
      - numpydoc==1.7.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - ollama==0.4.7
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.4
      - openxlab==0.0.38
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - patsy==0.5.6
      - pillow==10.3.0
      - plotly==5.22.0
      - pluggy==1.5.0
      - portalocker==2.10.0
      - preshed==3.0.9
      - proglog==0.1.10
      - prompt-toolkit==3.0.43
      - pthflops==0.4.2
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydocstyle==6.3.0
      - pyfast==4.9.2
      - pyflakes==3.2.0
      - pygithub==2.3.0
      - pyhrv==0.4.1
      - pyjwt==2.8.0
      - pylint==3.1.0
      - pylint-venv==3.0.3
      - pyls-spyder==0.4.0
      - pynacl==1.5.0
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - python-dateutil==2.9.0.post0
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.12.0
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pyts==0.13.0
      - pytz==2023.4
      - pyuca==1.2
      - pywavelets==1.6.0
      - pyxdg==0.28
      - pyyaml==6.0.1
      - qdarkstyle==3.2.3
      - qstylizer==0.2.3
      - qtawesome==1.4.0
      - qtconsole==5.6.1
      - qtpy==2.4.1
      - referencing==0.35.0
      - regex==2024.4.28
      - requests==2.28.2
      - rich==13.4.2
      - rope==1.13.0
      - rpds-py==0.18.0
      - rtree==1.2.0
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - sentry-sdk==2.0.1
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - shapely==2.0.4
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - smart-open==7.0.5
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spectrum==0.8.1
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - spyder==6.0.5
      - spyder-kernels==3.0.4
      - srsly==2.4.8
      - stack-data==0.6.3
      - statsmodels==0.14.3
      - superqt==0.6.7
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.3.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - text-unidecode==1.3
      - textdistance==4.6.2
      - thinc==8.3.2
      - threadpoolctl==3.4.0
      - three-merge==0.1.1
      - tifffile==2024.4.24
      - timm==0.9.16
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.12.4
      - torch==2.2.2
      - torch-geometric==2.5.3
      - torchaudio==2.2.2
      - torchinfo==1.8.0
      - torchmetrics==1.3.2
      - torchvision==0.17.2
      - tqdm==4.65.2
      - transformers==4.40.1
      - triton==2.2.0
      - tsai==0.3.9
      - tsaug==0.2.1
      - typer==0.12.5
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - ujson==5.9.0
      - ultralytics-thop==2.0.0
      - umap-learn==0.5.6
      - urllib3==1.26.18
      - vidaug==0.1
      - wandb==0.16.6
      - wasabi==1.1.3
      - watchdog==4.0.0
      - weasel==0.4.1
      - webencodings==0.5.1
      - whatthepatch==1.0.5
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - wurlitzer==3.0.3
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /home/user01/anaconda3/envs/pyt
